[package]
name = "randomSQL"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
dirs = "5.0.1"
fake = "2.7.0"
rand = "0.8.5"
shlex = "1.1.0"
